In [3]:
# importing modules required for the optimization
import numpy as np
import statsmodels.api as sm
from scipy.optimize import minimize

In [4]:
# Generate some fake data.  
# obs is number of observations.
# params is the number of parameters to be estimated ignoring the constant.  
# It is adjusted to include a constant using statsmodels "add_constant"

obs = 2000
params = 1

params = params + 1
beta = np.random.randn(params, 1)
beta0 = np.zeros((params, 1))
X = np.random.randn(obs, params-1)
X = sm.add_constant(X)
y = np.dot(X, beta) + np.random.randn(obs, 1)

In [12]:
# This is least squares using BFGS to recover the covariance matrix.  
# b is beta.  y and X are endog and exog respectively passed to the function.
# Scratch space for beta is necessary.

def func(b, y, X, obs, params):
    bv = b.view()
    bv.shape = params, 1
    e = y - np.dot(X, bv)
    return np.array(np.sum(e**2))

def func_grad(b, y, X, obs, params):
    bv = b.view()
    bv.shape = params, 1
    foc = -np.sum(X * (y - np.dot(X, bv)), axis=0)
    return np.array(foc)

res = minimize(func, beta0, args=(y, X, obs, params), method='BFGS', 
               jac=func_grad, options={'disp': True, 'maxiter':1000})

Optimization terminated successfully.
         Current function value: 2047.839620
         Iterations: 5
         Function evaluations: 10
         Gradient evaluations: 10


In [13]:
# configure the matrices for the variance and the error

betahat = res.x.reshape((params, 1))
e = y - np.dot(X, betahat)
s2 = np.dot(np.transpose(e), e)/(obs - params)
cov = s2*res.hess_inv

se, t = np.zeros((params, 1)), np.zeros((params, 1))

for i in range(0, params):
    se[i] = np.sqrt(cov[i,i])
    t[i] = res.x[i]/np.sqrt(cov[i,i])

In [14]:
# Display beta from the DGP, betahats, their standard errors, and their t-statistics.

print beta
print betahat
print se
print t

[[ 0.31350182]
 [ 0.89056753]]
[[ 0.34729575]
 [ 0.87543959]]
[[ 0.0226411 ]
 [ 0.02265815]]
[[ 15.33917207]
 [ 38.63685554]]


In [16]:
# Generate some fake data.  
# obs is number of observations.
# params is the number of parameters to be estimated ignoring the constant.  
# It is adjusted to include a constant using statsmodels "add_constant"

obs = 5000
params = 1

params = params + 1
beta = np.random.randn(params, 1)
beta0 = np.zeros((params, 1))
X = np.random.randn(obs, params-1)
X = sm.add_constant(X)
y = np.dot(X, beta) + np.random.randn(obs, 1)

In [17]:
# This is least squares using BFGS to recover the covariance matrix.  
# b is beta.  y and X are endog and exog respectively passed to the function.
# Scratch space for beta is necessary.

def func(b, y, X, obs, params):
    bv = b.view()
    bv.shape = params, 1
    e = y - np.dot(X, bv)
    return np.array(np.sum(e**2))

def func_grad(b, y, X, obs, params):
    bv = b.view()
    bv.shape = params, 1
    foc = -np.sum(X * (y - np.dot(X, bv)), axis=0)
    return np.array(foc)

res = minimize(func, beta0, args=(y, X, obs, params), method='BFGS', 
               jac=func_grad, options={'disp': True, 'maxiter':1000})

Optimization terminated successfully.
         Current function value: 4947.025424
         Iterations: 5
         Function evaluations: 12
         Gradient evaluations: 12


In [18]:
# configure the matrices for the variance and the error

betahat = res.x.reshape((params, 1))
e = y - np.dot(X, betahat)
s2 = np.dot(np.transpose(e), e)/(obs - params)
cov = s2*res.hess_inv

se, t = np.zeros((params, 1)), np.zeros((params, 1))

for i in range(0, params):
    se[i] = np.sqrt(cov[i,i])
    t[i] = res.x[i]/np.sqrt(cov[i,i])

In [19]:
print beta
print betahat
print se
print t

[[ 1.01448344]
 [ 0.74906768]]
[[ 0.99853222]
 [ 0.773718  ]]
[[ 0.01407067]
 [ 0.01401307]]
[[ 70.96551466]
 [ 55.21400972]]


In this case, when we change the number of observations for the sample in the function (2000 aand 5000 vs 1000 initially), we get higher levels of the t-statistic, therefore demostrating that the estimated mean of the observated values lies far away from the mean of the population the model that is trying to explain.